import { describe, expect, test, vi } from "vitest";

import { getOrCreateCachedClient } from "./prisma-cache";

describe("getOrCreateCachedClient", () => {
  test("reuses a client generated by the same constructor", () => {
    const clientConstructor = class Client {};
    const client = new clientConstructor();
    const createClient = vi.fn(() => new clientConstructor());

    const result = getOrCreateCachedClient(
      { client, clientConstructor },
      clientConstructor,
      createClient,
    );

    expect(result.client).toBe(client);
    expect(createClient).not.toHaveBeenCalled();
  });

  test("replaces a stale client after Prisma generation changes", () => {
    const previousConstructor = class Client {};
    const currentConstructor = class Client {};
    const previousClient = new previousConstructor();
    const currentClient = new currentConstructor();
    const createClient = vi.fn(() => currentClient);

    const result = getOrCreateCachedClient(
      { client: previousClient, clientConstructor: previousConstructor },
      currentConstructor,
      createClient,
    );

    expect(result).toEqual({
      client: currentClient,
      clientConstructor: currentConstructor,
    });
    expect(createClient).toHaveBeenCalledOnce();
  });
});
