[tool.poetry]
name = "import-job"
version = "0.0.1"
description = "import job description based on url"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
openai = "<2"
langchain-community = ">=0.0.7,<0.2"
langchain-core = ">=0.1.4,<0.2"
langchain-openai = "^0.1.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "import_job.chain"
export_attr = "chain"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
